spring:
  application:
    name: lovable-app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/lovable_app_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 5001
